# Домашнє завдання №4: NumPy

Усі завдання виконано за допомогою бібліотеки **NumPy**. Для відтворюваності випадкових значень використано фіксований seed.

In [1]:
import numpy as np

np.set_printoptions(precision=4, suppress=True)
rng = np.random.default_rng(42)
print(f'NumPy version: {np.__version__}')

NumPy version: 2.5.2


# Основна частина

### 1. Вектор із перших 10 натуральних чисел

In [2]:
vector_1 = np.arange(1, 11)
print(vector_1)

[ 1  2  3  4  5  6  7  8  9 10]


### 2. Матриця 3×3, заповнена нулями

In [3]:
matrix_2 = np.zeros((3, 3), dtype=int)
print(matrix_2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


### 3. Матриця 5×5 із випадковими цілими числами від 1 до 10

In [4]:
matrix_3 = rng.integers(1, 11, size=(5, 5))
print(matrix_3)

[[ 1  8  7  5  5]
 [ 9  1  7  3  1]
 [ 6 10  8  8  8]
 [ 8  6  2  9  5]
 [ 6  4  2 10  8]]


### 4. Матриця 4×4 із випадковими дійсними числами від 0 до 1

In [5]:
matrix_4 = rng.random((4, 4))
print(matrix_4)

[[0.8228 0.4434 0.2272 0.5546]
 [0.0638 0.8276 0.6317 0.7581]
 [0.3545 0.9707 0.8931 0.7784]
 [0.1946 0.4667 0.0438 0.1543]]


### 5. Поелементні додавання, віднімання та множення двох векторів

In [6]:
vector_5a = rng.integers(1, 11, size=5)
vector_5b = rng.integers(1, 11, size=5)
print('a =', vector_5a)
print('b =', vector_5b)
print('a + b =', vector_5a + vector_5b)
print('a - b =', vector_5a - vector_5b)
print('a * b =', vector_5a * vector_5b)

a = [ 7  8  7 10  8]
b = [ 4 10  5  4 10]
a + b = [11 18 12 14 18]
a - b = [ 3 -2  2  6 -2]
a * b = [28 80 35 40 80]


### 6. Скалярний добуток двох векторів розміром 7

In [7]:
vector_6a = np.array([1, 2, 3, 4, 5, 6, 7])
vector_6b = np.array([7, 6, 5, 4, 3, 2, 1])
dot_product_6 = np.dot(vector_6a, vector_6b)
print('a =', vector_6a)
print('b =', vector_6b)
print('Скалярний добуток =', dot_product_6)

a = [1 2 3 4 5 6 7]
b = [7 6 5 4 3 2 1]
Скалярний добуток = 84


### 7. Добуток матриць розміром 2×2 та 2×3

In [8]:
matrix_7a = rng.integers(1, 11, size=(2, 2))
matrix_7b = rng.integers(1, 11, size=(2, 3))
matrix_product_7 = matrix_7a @ matrix_7b
print('A =\n', matrix_7a)
print('B =\n', matrix_7b)
print('A @ B =\n', matrix_product_7)

A =
 [[4 1]
 [5 8]]
B =
 [[2 5 2]
 [7 5 4]]
A @ B =
 [[15 25 12]
 [66 65 42]]


### 8. Обернена матриця для випадкової матриці 3×3

In [9]:
# Генеруємо матрицю доти, доки вона не буде невиродженою.
while True:
    matrix_8 = rng.integers(1, 11, size=(3, 3))
    if not np.isclose(np.linalg.det(matrix_8), 0):
        break

inverse_8 = np.linalg.inv(matrix_8)
print('A =\n', matrix_8)
print('det(A) =', np.linalg.det(matrix_8))
print('A⁻¹ =\n', inverse_8)
print('Перевірка A @ A⁻¹ =\n', matrix_8 @ inverse_8)

A =
 [[ 3  6  7]
 [10  5  2]
 [ 9  7  8]]
det(A) = -119.00000000000003
A⁻¹ =
 [[-0.2185 -0.0084  0.1933]
 [ 0.521   0.3277 -0.5378]
 [-0.2101 -0.2773  0.3782]]
Перевірка A @ A⁻¹ =
 [[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]


### 9. Транспонування випадкової матриці 4×4

In [10]:
matrix_9 = rng.random((4, 4))
transposed_9 = matrix_9.T
print('A =\n', matrix_9)
print('Aᵀ =\n', transposed_9)

A =
 [[0.3124 0.8323 0.8048 0.3875]
 [0.2883 0.6825 0.1398 0.1999]
 [0.0074 0.7869 0.6649 0.7052]
 [0.7807 0.4589 0.5687 0.1398]]
Aᵀ =
 [[0.3124 0.2883 0.0074 0.7807]
 [0.8323 0.6825 0.7869 0.4589]
 [0.8048 0.1398 0.6649 0.5687]
 [0.3875 0.1999 0.7052 0.1398]]


### 10. Множення цілочисельної матриці 3×4 на вектор розміром 4

In [11]:
matrix_10 = rng.integers(1, 11, size=(3, 4))
vector_10 = rng.integers(1, 11, size=4)
product_10 = matrix_10 @ vector_10
print('A =\n', matrix_10)
print('x =', vector_10)
print('A @ x =', product_10)

A =
 [[3 2 5 7]
 [7 5 9 6]
 [1 8 6 7]]
x = [6 6 1 6]
A @ x = [ 77 117 102]


### 11. Множення дійсної матриці 2×3 на вектор розміром 3

In [12]:
matrix_11 = rng.random((2, 3))
vector_11 = rng.random(3)
product_11 = matrix_11 @ vector_11
print('A =\n', matrix_11)
print('x =', vector_11)
print('A @ x =', product_11)

A =
 [[0.304  0.0308 0.4367]
 [0.2146 0.4085 0.8534]]
x = [0.2339 0.0583 0.2814]
A @ x = [0.1958 0.3142]


### 12. Поелементне множення двох матриць 2×2

In [13]:
matrix_12a = rng.integers(1, 11, size=(2, 2))
matrix_12b = rng.integers(1, 11, size=(2, 2))
elementwise_product_12 = matrix_12a * matrix_12b
print('A =\n', matrix_12a)
print('B =\n', matrix_12b)
print('A * B =\n', elementwise_product_12)

A =
 [[10  3]
 [ 5  7]]
B =
 [[2 6]
 [6 8]]
A * B =
 [[20 18]
 [30 56]]


### 13. Матричний добуток двох матриць 2×2

In [14]:
matrix_13a = rng.integers(1, 11, size=(2, 2))
matrix_13b = rng.integers(1, 11, size=(2, 2))
matrix_product_13 = matrix_13a @ matrix_13b
print('A =\n', matrix_13a)
print('B =\n', matrix_13b)
print('A @ B =\n', matrix_product_13)

A =
 [[10  7]
 [ 5  5]]
B =
 [[5 9]
 [4 2]]
A @ B =
 [[ 78 104]
 [ 45  55]]


### 14. Сума елементів випадкової матриці 5×5

In [15]:
matrix_14 = rng.integers(1, 101, size=(5, 5))
sum_14 = np.sum(matrix_14)
print('A =\n', matrix_14)
print('Сума елементів =', sum_14)

A =
 [[34  3 11 10 78]
 [73 70 47 72 17]
 [91 51 94 16 50]
 [70 50 45 17 39]
 [24 31 69 64 61]]
Сума елементів = 1187


### 15. Різниця двох випадкових матриць 4×4

In [16]:
matrix_15a = rng.integers(1, 11, size=(4, 4))
matrix_15b = rng.integers(1, 11, size=(4, 4))
difference_15 = matrix_15a - matrix_15b
print('A =\n', matrix_15a)
print('B =\n', matrix_15b)
print('A - B =\n', difference_15)

A =
 [[ 4 10  1  4]
 [ 2  4 10  4]
 [10  5  7  5]
 [ 3  8 10  3]]
B =
 [[ 8  3  8  8]
 [ 5  8  3  1]
 [ 1  5 10  2]
 [ 5  8  3  8]]
A - B =
 [[-4  7 -7 -4]
 [-3 -4  7  3]
 [ 9  0 -3  3]
 [-2  0  7 -5]]


### 16. Вектор-стовпчик із сумами елементів кожного рядка

In [17]:
matrix_16 = rng.random((3, 3))
row_sums_16 = np.sum(matrix_16, axis=1, keepdims=True)
print('A =\n', matrix_16)
print('Суми рядків =\n', row_sums_16)
print('Розмір результату:', row_sums_16.shape)

A =
 [[0.5792 0.1768 0.8566]
 [0.7585 0.7195 0.4321]
 [0.6273 0.5841 0.6498]]
Суми рядків =
 [[1.6126]
 [1.9101]
 [1.8613]]
Розмір результату: (3, 1)


### 17. Матриця квадратів цілих чисел

In [18]:
matrix_17 = np.array([[1, -2, 3, 4],
                      [-5, 6, -7, 8],
                      [9, 10, -11, 12]])
squared_17 = np.square(matrix_17)
print('A =\n', matrix_17)
print('A² (поелементно) =\n', squared_17)

A =
 [[  1  -2   3   4]
 [ -5   6  -7   8]
 [  9  10 -11  12]]
A² (поелементно) =
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


### 18. Квадратні корені елементів вектора

In [19]:
vector_18 = rng.integers(1, 51, size=4)
square_roots_18 = np.sqrt(vector_18)
print('a =', vector_18)
print('√a =', square_roots_18)

a = [16 32  5 38]
√a = [4.     5.6569 2.2361 6.1644]


# Завдання 2 (додаткове)

### 1. Заміна всіх непарних чисел на −1

In [20]:
arr_extra_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_extra_1[arr_extra_1 % 2 != 0] = -1
print(arr_extra_1)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### 2. Перетворення 1D-масиву на 2D-масив із двома рядками

In [21]:
arr_extra_2 = np.arange(1, 11)
matrix_extra_2 = arr_extra_2.reshape(2, -1)
print('1D:', arr_extra_2)
print('2D:\n', matrix_extra_2)

1D: [ 1  2  3  4  5  6  7  8  9 10]
2D:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### 3. Вертикальне об’єднання двох двовимірних масивів

In [22]:
a_extra_3 = np.array([[1, 2, 3], [4, 5, 6]])
b_extra_3 = np.array([[7, 8, 9], [10, 11, 12]])
stacked_extra_3 = np.vstack((a_extra_3, b_extra_3))
print(stacked_extra_3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### 4. Створення заданого шаблону без hard coding

In [23]:
a_extra_4 = np.array([1, 2, 3])
pattern_extra_4 = np.concatenate((np.repeat(a_extra_4, 3), np.tile(a_extra_4, 3)))
print(pattern_extra_4)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


### 5. Спільні елементи двох масивів

In [24]:
a_extra_5 = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b_extra_5 = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
common_extra_5 = np.intersect1d(a_extra_5, b_extra_5)
print(common_extra_5)

[2 4]


### 6. Індекси п’яти найбільших значень

In [25]:
np.random.seed(100)
a_extra_6 = np.random.uniform(1, 50, 20)
top5_indices_extra_6 = np.argsort(a_extra_6)[-5:][::-1]
print('a =', a_extra_6)
print('Індекси (за спаданням значень) =', top5_indices_extra_6)
print('Значення =', a_extra_6[top5_indices_extra_6])

a = [27.6268 14.6401 21.8014 42.394   1.2312  6.9569 33.8667 41.4668  7.6986
 29.1796 44.6748 11.2509 10.0811  6.3105 11.7652 48.9526 40.7725  9.4251
 40.995  14.4296]
Індекси (за спаданням значень) = [15 10  3  7 18]
Значення = [48.9526 44.6748 42.394  41.4668 40.995 ]


### 7. Видалення всіх значень NaN

In [26]:
a_extra_7 = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
without_nan_extra_7 = a_extra_7[~np.isnan(a_extra_7)]
print(without_nan_extra_7)

[1. 2. 3. 5. 6. 7.]


### 8. Евклідова відстань між двома масивами

In [27]:
a_extra_8 = np.array([1, 2, 3, 4, 5])
b_extra_8 = np.array([4, 5, 6, 7, 8])
distance_extra_8 = np.linalg.norm(a_extra_8 - b_extra_8)
print('Евклідова відстань =', distance_extra_8)

Евклідова відстань = 6.708203932499369


### 9. Індекс п’ятого входження числа 1

In [28]:
x_extra_9 = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
fifth_index_extra_9 = np.flatnonzero(x_extra_9 == 1)[4]
print('Індекс п’ятого входження числа 1 =', fifth_index_extra_9)

Індекс п’ятого входження числа 1 = 8


### 10. Позначення повторних входжень як True

In [29]:
np.random.seed(100)
a_extra_10 = np.random.randint(0, 5, 10)
duplicates_extra_10 = np.ones(a_extra_10.size, dtype=bool)
first_indices_extra_10 = np.unique(a_extra_10, return_index=True)[1]
duplicates_extra_10[first_indices_extra_10] = False
print('a =', a_extra_10)
print('Повторні входження =', duplicates_extra_10)

a = [0 0 3 0 2 4 2 2 2 2]
Повторні входження = [False  True False  True False False  True  True  True  True]
